"""add supervisor models

Revision ID: b0b0d76686ff
Revises: 5bc98d00cf95
Create Date: 2025-11-11 03:19:45.962679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b0b0d76686ff'
down_revision: Union[str, Sequence[str], None] = '5bc98d00cf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowedstudent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowedstudent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowedstudent_student_number'), ['student_number'], unique=True)

    op.create_table('allowedteacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowedteacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowedteacher_university_email'), ['university_email'], unique=True)

    op.create_table('semesterresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semesterresult')
    with op.batch_alter_table('allowedteacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowedteacher_university_email'))

    op.drop_table('allowedteacher')
    with op.batch_alter_table('allowedstudent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowedstudent_student_number'))

    op.drop_table('allowedstudent')
    # ### end Alembic commands ###
